name: 'dbt_bigquery_info_schema'
version: '1.0.0'
config-version: 2

profile: 'dbt_bigquery_info_schema'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_bigquery_info_schema:
    staging:
      +materialized: view

vars:
  dbt_bigquery_info_schema:
    flat_rate_pricing_enabled: false
