config-version: 2
name: 'bigquery_info_schema'
version: '0.0.1'

models:
  bigquery_info_schema:
    +schema: bq_info_schema

vars:
  bigquery_info_schema:
    capacity_compute_pricing_enabled: false
    logical_active_rate: 0.02
    logical_long_term_rate: 0.01
    physical_active_rate: 0.04
    physical_long_term_rate: 0.02
